In [1]:
# Why use NumPy?
import time
import numpy as np
x = np.random.random(100_000_000)

# Case 1
start = time.time()
sum(x) / len(x)
print(time.time() - start)

# Case 2
start = time.time()
np.mean(x)
print(time.time() - start)

9.102853536605835
0.10512185096740723


In [11]:
x = np.array([1, 2, 3, 4, 5])
print(x)
print(x.ndim)
print(type(x))
print(x.dtype)
print(x.shape)

[1 2 3 4 5]
1
<class 'numpy.ndarray'>
int64
(5,)


In [12]:
y = np.array([[1, 2, 3], [4, 5, 6]])
print(y)
print(x.ndim)
print(type(y))
print(y.dtype)
print(y.shape)
print(y.size)

[[1 2 3]
 [4 5 6]]
1
<class 'numpy.ndarray'>
int64
(2, 3)
6


In [10]:
z = np.array([1, 5., '54'], dtype=np.int32)
print(z)
print(z.dtype)

[ 1  5 54]
int32


In [20]:
print(np.zeros((2, 3), dtype=np.float64))
print(np.ones((3, 2), dtype=np.int8))
print(np.full((4,5), 7))
print(np.eye(4))
print(np.diag((10, 20, 30, 40)))
print(np.arange(3))
print(np.arange(3, 6))
print(np.arange(3, 6, 0.33))

[[0. 0. 0.]
 [0. 0. 0.]]
[[1 1]
 [1 1]
 [1 1]]
[[7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 40]]
[0 1 2]
[3 4 5]
[3.   3.33 3.66 3.99 4.32 4.65 4.98 5.31 5.64 5.97]


In [28]:
print(np.linspace(0, 5, 10))
print(np.linspace(0, 5, 10, endpoint=False))
print(np.arange(10).reshape((2,5)))
np.linspace(0, 5, 10, endpoint=False).reshape((5, 2))

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]
[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
[[0 1 2 3 4]
 [5 6 7 8 9]]


array([[0. , 0.5],
       [1. , 1.5],
       [2. , 2.5],
       [3. , 3.5],
       [4. , 4.5]])

In [35]:
print(np.random.random((3, 5)))
print(np.random.randint(2, 178, (3, 2)))
x = np.random.normal(0, 1, size=(10, 10))
print(x.mean())
print(x.std())
print(x.max())
print(x.min())

[[0.99099257 0.42950191 0.08925327 0.01177932 0.72194063]
 [0.63243787 0.99780859 0.60486009 0.98524841 0.35697773]
 [0.76137643 0.32282664 0.53770153 0.81278273 0.81534545]]
[[176  70]
 [164 135]
 [ 25  76]]
-0.003206499714861486
1.028349482112626
2.451633120246915
-2.0397762680170195
